# file: roles/common/tasks/main.yml
---

- name: Set up Discourse Docker container contents
  git: >
    repo=https://github.com/discourse/discourse_docker.git
    dest={{ discourse.dir }}
    update=no

- name: Create the data.yml PostgreSQL and Redis configuration file
  template: src=data.j2
    dest={{ discourse.dir }}/containers/data.yml
  notify:
    - Build Discourse data

- name: Create the web.yml Application server configuration file
  template: src=web.j2
    dest={{ discourse.dir }}/containers/web.yml
  notify:
    - Build Discourse web
